[colors]
[colors.primary]
background = "#050505"
foreground = "#D6D0C5"

[colors.normal]
black   = "#050505"
red     = "#da614e" # Blood Ink
green   = "#8B9388" # Dein optimiertes Blau-Grau (jetzt im Green Slot)
yellow  = "#51605b" # Gold
blue    = "#75897F" # Jade im Blue Slot (sehr majestätisch)
magenta = "#C2A46D" # Bronze im Magenta Slot
cyan    = "#717C7C" # Grey-Teal
white   = "#D6D0C5"

[colors.bright]
black   = "#404040"
red     = "#df6124"
green   = "#525e5a"
yellow  = "#8B9388"
blue    = "#75897F" # Heller Akzent
magenta = "#C2A46D"
cyan    = "#52565e" # Jade Highlight
white   = "#FFF9ED"

[colors.cursor]
text   = "#050505"
cursor = "#75897F" # Jade Cursor passend zum Dragon-Thema